### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Rockster160** [Rockster160/ParkourUtah#1]
- [x] BUG: Created non-repeating events seems to create a double event.
- [x] Style Header
- [x] Style error messages
- [x] Make Flashes auto-disappear
- [ ] Style event page
- [ ] S. Calendar page
- [ ] S. Day page
- [ ] S. New event
- [ ]  S. User pages
- [ ] Create shop
- [ ] Connect Stripe
- [ ] Parkour Spot Finder
- [x] BUG: Moving month to month does not pass the correct params (After clicking button, run JS update function?)
- [x] Jquery Date Picker - Admin tools
- [x] Links to events on day pages
- [x] Move calendar to own page - Listing of locations, forward to page with auto-load of events at that location
- [x] Load PKUT images

**Comment by Rockster160** [comment]
calendar.js line 19-
$('.back-month .forward-month').click(function() {
  update();
})

**Comment by Rockster160** [comment]
All of these things are completed.
